### ISSUE TITLE
feature request: match_array

### ISSUE THREAD

**Issue by rdpoor** [zenspider/minitest-matchers#5]
I'm glad to have made the switch to MiniTest from RSpec.  

But one thing I miss from RSpec is the ability to compare two arrays without regard to the order of the elements.  This `match_array` matcher is implemented in RSpec in:

```
https://github.com/dchelimsky/rspec/blob/master/lib/spec/matchers/match_array.rb
```

(rather elegant, IMO), and it's simple enough that I can replicate it as a custom MiniTest matcher in my project.  

But it might make a nice permanent addition to minitest-matchers.

**Comment by wojtekmach** [comment]
I don't think this belongs in this gem, since this is just a bridge to use matchers (imported from RSpec) but not a place to define new matchers. If you're still interested in this, probably a writing a custom plugin, perhaps minitest-match-array or something, is the way to go. In that plugin, you could define both assert_match_array & must_match_array so that both minitest test & spec users could use it. Sorry for a late reply!
